/*
 * generated by Xtext 2.34.0
 */
package ctwedge.ui;

import com.google.inject.Injector;
import ctwedge.ui.internal.CtwedgeActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CTWedgeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CtwedgeActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CtwedgeActivator activator = CtwedgeActivator.getInstance();
		return activator != null ? activator.getInjector(CtwedgeActivator.CTWEDGE_CTWEDGE) : null;
	}

}
